version: "3.0"

services:
  cb:
    image: meepdocker/classroom-bot:latest
    container_name: cb
    restart: "no" # see https://github.com/compose-spec/compose-spec/blob/master/spec.md#restart
    ports:
      - "443:443"
    environment:
      BOT_TOKEN: # Token here
      BOT_ADMINS: # JSON array of strings with admins id's
      MONGO_URL: # MongoDB Url here
      DATABASE_NAME: # Database name here
      MASTER_KEY: # Master key here
